Add additional configurations
peerpower/django-boilerplate pull request #7
Opened 2022-12-08 03:43 UTC by shannonssd

2022-12-08 07:58 UTC, jozeffrtus requested changes

2022-12-08 07:58 UTC, jozeffrtus commented on README.md
> +        * Line 41: ```django_settings_module = "app_template.project.settings.base"```
Maybe `settings.dev` instead. `base` is not supposed to be directly used, it is only place for defining settings common for dev, test and live environments.

2022-12-08 07:58 UTC, jozeffrtus commented on pyproject.toml
> +django_settings_module = "app_template.project.settings.base"
Maybe `settings.dev` instead. `base` is not supposed to be directly used, it is only place for defining settings common for dev, test and live environments.

2022-12-12 02:23 UTC, shannonssd commented on pyproject.toml
> +django_settings_module = "app_template.project.settings.base"
Noted, will change it. I think the `investor-reporting` repo needs to be changed as well.
https://github.com/peerpower/investor-reporting/blob/main/pyproject.toml

2022-12-12 04:22 UTC, chawaponake commented on pyproject.toml
> +django_settings_module = "app_template.project.settings.base"
@freyadam Please note.

2022-12-12 04:22 UTC, chawaponake approved these changes
LGTM

2022-12-12 07:48 UTC, jozeffrtus approved these changes

2022-12-12 10:06 UTC, merged